
parameterSetList:
  - name: "List of correlated normalization parameters"
    isEnabled: true
    useEigenDecompInFit: false
    allowPca: false
    covarianceMatrixFilePath: "./example/advanced/simpleFit/inputs/parameters/flux/covarianceFile.root"
    covarianceMatrixTMatrixD: "covarianceMatrix"
    useOnlyOneParameterPerEvent: true
    dialSetDefinitions:
      - applyOnDataSets: [ "*" ]
        parametersBinningPath: "./example/advanced/simpleFit/inputs/parameters/flux/binning.txt"
        printDialsSummary: true
    printDialSetsSummary: true

  - name: "List of Free Normalization parameters"
    isEnabled: true
    nominalStepSize: 0.1
    useOnlyOneParameterPerEvent: true
    dialSetDefinitions:
      - applyOnDataSets: [ "*" ]
        parametersBinningPath: "./example/advanced/simpleFit/inputs/parameters/free/binning.txt"

  - name: "Dummy Systematics"
    isEnabled: true
    nominalStepSize: 0.1
    parameterDefinitions:
      - name: "Graph interpolation parameter"
        isEnabled: true
        priorType: Gaussian
        priorValue: 1.0
        isFixed: false
        isThrown: false
        parameterStepSize: 0.1
        parameterLimits: [0.0, 2.0]
        physicalLimits: [0.0, 2.0]
        throwLimits: [0.0, 2.0]
        dialSetDefinitions:
          - dialType: Graph
            dialLeafName: par3_TGraph
            applyOnDataSets: [ "My dataset 1" ]
            allowDialExtrapolation: false
            minDialResponse: 0.0
            maxDialResponse: 3.0
