outputFolder: "./example/advanced/output/fit_natural"
minGundamVersion: 1.9.0

fitterEngineConfig:

  minimizerConfig:
    type: "RootMinimizer"

  likelihoodInterfaceConfig:

    dataSetList: "./example/advanced/simpleFit/inputs/datasets/config.yaml"

    plotGeneratorConfig: "./example/advanced/simpleFit/inputs/plots/config.yaml"

    propagatorConfig:
      sampleSetConfig: "./example/advanced/simpleFit/inputs/samples/config.yaml"
      parametersManagerConfig: "./example/advanced/simpleFit/inputs/parameters/config_natural.yaml"
